### ISSUE TITLE
__udivmoddi4: integer division by zero

### ISSUE THREAD

**Issue by pipcet** [pipcet/asmjs#2]
There appears to be an Ion bug resulting in some code throwing an integer division by zero exception even though the division is actually in a code path that is never followed.

https://bugzilla.mozilla.org/show_bug.cgi?id=1321189

**Comment by kripken** [comment]
A tangential issue, but instead of compiling udivmoddi4, you can translate it to a routine using native 64-bit operations, as [asm2wasm does](https://github.com/WebAssembly/binaryen/blob/master/src/asm2wasm.h#L1057). In a benchmark I see that giving a 2x speedup on a 32-bit machine. (There is a further 2x speedup by using native i64s in the main code, avoiding udivmoddi4 entirely.)

**Comment by pipcet** [comment]
That's a good point. I'd experimented with 64-bit operations on an older wasm version, but haven't really given much thought to how to combine 64 and 32 bit operations—it's harder for me since I use "registers", which are currently 32 bits, though there's no need for those as long as I don't have to save intermediate state to linear memory.

**Comment by pipcet** [comment]
Closing as the SpiderMonkey bug is now fixed.
